version: '3.9'

services:
  enterprise-service:
    image: jackal-game-enterprise-service
    build: ./jackal-game-enterprise-service/
    container_name: jackal-game-enterprise-service
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:${DB_PROTOCOL}://${DB_HOST}:${DB_INNER_PORT}/${DB_NAME}"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      LOBBY_SERVICE_API_URL: ${LOBBY_SERVICE_API_URL}
      VK_AUTH_URL: ${VK_AUTH_URL}
      VK_API_VERSION: ${VK_API_VERSION}
      YANDEX_AUTH_URL: ${YANDEX_AUTH_URL}
      ENTERPRISE_JWT_SECRET: ${ENTERPRISE_JWT_SECRET}
      ENTERPRISE_JWT_TIME_EXPIRATION_MS: ${ENTERPRISE_JWT_TIME_EXPIRATION_MS}
    depends_on:
      - enterprise-service-db
    restart: always
  enterprise-service-db:
    image: postgres
    container_name: jackal-game-enterprise-service-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_OUTER_PORT}:${DB_INNER_PORT}
  lobby-service:
    image: jackal-game-lobby-service
    build: ./jackal-game-lobby-service/
    container_name: jackal-game-lobby-service
    ports:
      - "8081:8081"
    environment:
      LOBBY_JWT_SECRET: ${LOBBY_JWT_SECRET}
    restart: always
  game-session-service:
    container_name: jackal-game-session-service
    image: jackal-game-session-service
    build: ./jackal-game-session-service/
    ports:
      - "8030:8030"
    environment:
      GAME_SESSION_SERVICE_PORT: "8030"
    restart: always
  client:
    image: jackal-game-client
    build: ./jackal-game-client/
    container_name: jackal-game-client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_VK_CLIENT_ID: ${REACT_APP_VK_CLIENT_ID}
      REACT_APP_YANDEX_CLIENT_ID: ${REACT_APP_YANDEX_CLIENT_ID}
      REACT_APP_ENTERPRISE_URL: ${REACT_APP_ENTERPRISE_URL}
      REACT_APP_LOBBY_SERVICE_URL: ${REACT_APP_LOBBY_SERVICE_URL}
      REACT_APP_GAME_SERVICE_URL: ${REACT_APP_GAME_SERVICE_URL}
    restart: always